# spring.cloud.stream.function.bindings.log|uppercase|log-in-0=input

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    function.definition: uppercase|respond
    stream:
      
      defaultBinder: kafka
      bindings:
        uppercase|respond-in-0: 
          group: uppercase-group
          destination: request-reply
          consumer:
            max-attempts: 1
#        uppercase|respond-out-0:
#          destination: request-mid-topic
#        respond-in-0: 
#          destination: request-reply
#          group: respond-group
#          consumer:
#            max-attempts: 1
#      rabbit:
#        bindings:
#          uppercase-in-0:
#            consumer:
#              #bindingRoutingKey: myRoutingKey 
#              autoBindDlq: true
#              queueNameGroupOnly: true
#              exchangeType: topic
#            #producer:
#              #routingKeyExpression: 'myRoutingKey'
#          respond-in-0:
#            consumer:
#              #bindingRoutingKey: myRoutingKey 
#              autoBindDlq: true
#              queueNameGroupOnly: true
#              exchangeType: topic
#            #producer:
#              #routingKeyExpression: 'myRoutingKey'












#      binders:
#        rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672
#                username: guest 
#                password: guest
#                virtual-host: /
#    rabbit:
#      bindings:
#        uppercaseRespondInput:
#          consumer:
#            #bindingRoutingKey: myRoutingKey
#            autoBindDlq: true
#            queueNameGroupOnly: true
#            exchangeType: topic
#          #producer:
#            #routingKeyExpression: 'myRoutingKey'

